version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt

  build:
    commands:
      - echo Building the Flask app...

  post_build:
    commands:
      - echo Packaging the application for deployment...
      - zip -r deployment-package.zip .
      - echo Build and packaging completed successfully!

artifacts:
  files:
    - deployment-package.zip

cache:
  paths:
    - /root/.cache/pip
