version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - echo "Starting Build"
      - pip install -r requirements.txt
      - python -m unittest discover tests

  build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*' 
